"""
The ISMIP6 initMIP Atlas.
"""

from __future__ import absolute_import, division, print_function, unicode_literals

from livvkit.util.functions import Optional
from livvkit.util import elements


def run(name, config):
    """
    Runs the analysis.

    Args:
        name: The name of the test
        config: A dictionary representation of the configuration file

    Returns:
       The result of elements.page with the list of elements to display
    """
    
    element_list = elements.error("Unimplemented test", "This test contains no analysis code!")
    
    return elements.page(name, __doc__, element_list)


def print_summary():
    """
    Print out a summary generated by this module's summarize_result method
    """
    raise NotImplementedError


def summarize_result():
    """
    Provides a snapshot of the results of the analysis to be provided
    to the sumamry as well as being printed out in this module's
    print_summary method
    """
    raise NotImplementedError


def populate_metadata():
    """
    Generates the metadata responsible for telling the summary what
    is done by this module's run method
    """
    raise NotImplementedError
